package agentadapter

import (
	"encoding/json"
	"testing"
)

// V-M11-55 (M11_SRS FR-M11-25 / M11-B23): **하네스가 끼운 것은 대화가 아니다.**
//
// 접수: *"`<local-command-caveat>`, `<command-name>` … `[request interrupted by user]`
// 이것도 포함해서 시스템에 필요한 내용은 출력 안하는게 맞다"*.
//
// 목록은 **실측이다** (SRS §2.11 (6)): 사용자의 전사본 여덟 벌을 전수로 훑어 여섯 종을
// 셌고, 전부 **자기 항목을 통째로** 차지했다 — 사용자의 진짜 말과 섞인 경우가 한 건도
// 없었다. 그래서 판정이 **첫 토큰**이고, 본문을 잘라 내지 않는다.
func TestClaudeHarnessBlocks_NotDrawn(t *testing.T) {
	ad, err := Get("claude")
	if err != nil {
		t.Fatalf("claude 어댑터: %v", err)
	}

	// ① 하네스의 것 — 전사본에서도 스트림에서도 이벤트가 되지 않는다.
	//    실측한 여섯 종 그대로다 (§2.11 (6)).
	harness := []string{
		`<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>`,
		"<command-name>/login</command-name>\n            <command-message>login</command-message>\n            <command-args></command-args>",
		`<local-command-stdout>Login successful</local-command-stdout>`,
		"<task-notification>\n<task-id>b6vb8c535</task-id>\n<status>completed</status>\n</task-notification>",
		`[Request interrupted by user]`,
		`[Request interrupted by user for tool use]`,
	}
	for _, text := range harness {
		line := mustUserLine(t, text)
		evs, _ := ad.ParseHistory(line)
		for _, ev := range evs {
			if ev.Kind == EvUser {
				t.Fatalf("하네스 블록이 사용자의 말로 섰다: %.40q → %+v", text, ev)
			}
		}
	}

	// ② 사용자의 진짜 말은 그대로 남는다. **마커를 품고 있어도** 첫 토큰이 아니면
	//    그것은 사용자가 쓴 글이다 — 잘라 내는 손이 없어야 이 줄이 산다.
	for _, text := range []string{
		"안녕",
		"`<command-name>` 이 뭐야?",
		"로그에 [Request interrupted by user] 가 찍혔는데 왜지",
	} {
		line := mustUserLine(t, text)
		evs, ok := ad.ParseHistory(line)
		if !ok || len(evs) != 1 || evs[0].Kind != EvUser || evs[0].Text != text {
			t.Fatalf("사용자의 말이 사라졌다 (%q): ok=%v evs=%+v", text, ok, evs)
		}
	}

	// ③ 배열 content 의 text 항목도 같은 판정을 받는다 — 스트림이 그 모양으로 온다.
	evs, _ := ad.ParseHistory(`{"type":"user","message":{"content":[` +
		`{"type":"text","text":"[Request interrupted by user]"},` +
		`{"type":"text","text":"진짜 말"}]}}`)
	if len(evs) != 1 || evs[0].Kind != EvUser || evs[0].Text != "진짜 말" {
		t.Fatalf("배열 안에서 갈리지 않았다: %+v", evs)
	}

	// ④ 도구 결과는 건드리지 않는다 — 하네스의 것이 아니라 **에이전트가 한 일**이다.
	evs, _ = ad.ParseHistory(`{"type":"user","message":{"content":[{"type":"tool_result",` +
		`"tool_use_id":"tu-1","content":"[Request interrupted by user]"}]}}`)
	if len(evs) != 1 || evs[0].Kind != EvToolEnd || evs[0].Text != "[Request interrupted by user]" {
		t.Fatalf("도구 결과가 걸러졌다: %+v", evs)
	}
}

// mustUserLine 은 `user` 전사본 한 줄을 만든다 — 인용을 손으로 짜면 마커가 든 글에서
// 틀리기 쉽다.
func mustUserLine(t *testing.T, text string) string {
	t.Helper()
	b, err := json.Marshal(map[string]any{
		"type":    "user",
		"message": map[string]any{"content": text},
	})
	if err != nil {
		t.Fatalf("줄을 만들지 못했다: %v", err)
	}
	return string(b)
}
